# Generated by Django 5.2 on 2025-04-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='category',
            field=models.CharField(default='lost', max_length=50),
        ),
    ]
